"""empty message

Revision ID: f91e2cda01e4
Revises: 484aab52a5b9
Create Date: 2024-01-26 01:26:01.594199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91e2cda01e4'
down_revision = '484aab52a5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('selected_options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_options', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
